### ISSUE TITLE
rhel 7 options for hpe experimenting

### ISSUE THREAD

**Issue by jhansonhpe** [baallan/distribution#4]
- I  changed options to enable libgenders and etc. 
- Some minor hacks with ZAP_LIBPATH.

**Comment by baallan** [comment]
@jhansonhpe is there going to be a merge request associated with this? Also there's been a bit of refactoring (see toss3/ovis.spec.in) which may overlap in concerns.

**Comment by jhansonhpe** [comment]
@baallan let me refresh my copy of the repo and check. Note that HPE's cluster manager can use toss3 as it's base OS so I will ignore rhel for toss.
